matrix:
  include:

    - stage: flow
        language: node_js
        node_js: 11.14.0
        install: npm ci
        script: npm run flow

    - stage: build android
        language: android
        jdk: openjdk8
        android:
          components:
            - platform-tools
            - tools
            - build-tools-28.0.0
            - android-28
            - extra-android-m2repository
            - extra-google-google_play_services
            - extra-google-m2repository
        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
        before_install:
          - nvm install 11
          - node --version
          - chmod +x ./android/gradlew
        install: npm ci
        script:
          - cd android
          - ./gradlew assembleRelease
